# FMC Configuration File
EventMessage:
    Join: ""

MySQL:
    Host: ""
    Database: ""
    Port: 
    User: ""
    Password: ""
  
Socket:
    Server_Port: 

Discord:
    Token: ""
    GuildId: 
    ChannelId: 
    ChatChannelId: 
    AdminChannelId: 
    MineStatusChannelId: 
    AdCraRoleId: 
    ChatType: false
    Webhook_URL: ""
    InviteUrl: ""
    FirstJoinEmojiName: ""
    AddMemberEmojiName: ""
    JoinEmojiName: ""
    MoveEmojiName: ""
    ExitEmojiName: ""
    StartEmojiName: ""
    RequestEmojiName: ""
    RequestOKName: ""
    RequestCancelName: ""
    RequestNoResName: ""
    MenteOnEmojiName: ""
    MenteOffEmojiName: ""
    EndEmojiName: ""
    Presence:
        Activity: ""

Interval:
    Login: 
    Session: 3
    Request: 
    Start_Server: 

Debug:
    Mode: false
    ChannelId: 
    ChatChannelId: 
    AdminChannelId: 
    Webhook_URL: ""
    Test: 

Permission:
    Detail_Name:
        - something.permission
    Short_Name:
        - someperm

Conv:
    Mode: false
    Host: "localhost"
    EXE_Path: ""

Terraria:
    RestApiUrl: "http://localhost:7878"
    Token: ""
    ChannelId: 
    Exec_Path: ""